[package]
name = "meh"
version = "0.1.0"
authors = ["commit-person <commit-person@localhost>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
reqwest = "0.9.19"
serde_json = "1.0"
